### ISSUE TITLE
Last commit broke booting

### ISSUE THREAD

**Issue by Charlyo** [MSzturc/Lenovo-T460-OpenCore#10]
Dear MSzturc,

Your last commit (which was the update to 0.60.0) seems that it broke the boot process. Reverting to the previous commit solves the issue.

**Comment by aptonline** [comment]
Is that anything to do with secure boot flag that was added? I read something recently that the flag is enabled b default.  Think it was on Reddit but can't find article.

**Comment by MSzturc** [comment]
> Dear MSzturc,
> 
> Your last commit (which was the update to 0.60.0) seems that it broke the boot process. Reverting to the previous commit solves the issue.

Well that's new.. my dw1560 stopped working with the newer kext and my touchpad stopped working too ( have to switch to voodooRMI ). I will have a look on it the next couple of days.

**Comment by MSzturc** [comment]
I've updated the repo, please try the current version @Charlyo

**Comment by Charlyo** [comment]
Working as it should! Closing Issue!
