### ISSUE TITLE
DW1560 is not working with BrcmPatchRam 2.5.4

### ISSUE THREAD

**Issue by MSzturc** [MSzturc/Lenovo-T460-OpenCore#12]
After updating BrcmPatchRam to 2.5.4 the wlan card is no longer working.

**Comment by hylkefaber** [comment]
For me it was related to AirportBrcmFixup, reverting back to 2.0.7 fixed it, but [on the forums someone suggested a patch](https://www.insanelymac.com/forum/topic/315451-guide-lenovo-t460t470-macos-with-clover-and-opencore/?do=findComment&comment=2734525). Haven't tried it yet though!

**Comment by MSzturc** [comment]
fixed with 5daa949
