### ISSUE TITLE
Wifi Card question

### ISSUE THREAD

**Issue by aptonline** [MSzturc/Lenovo-T460-OpenCore#13]
I'm looking into getting the same Wi-Fi/BT card as you recommend in your setup but when I find the same one on eBay they specifically say they won't work in a Lenovo.  Any idea why this is?

https://www.ebay.co.uk/itm/PC-Hackintosh-wifi-Card-BCM94352Z-NGFF-WiFi-wlan-Card-867Mbps-Bluetooth-4-0-WiFi/172212358962?hash=item2818a80f32:g:2kEAAOSwQcJfImUy

**Comment by xqdxqd** [comment]
> I'm looking into getting the same Wi-Fi/BT card as you recommend in your setup but when I find the same one on eBay they specifically say they won't work in a Lenovo. Any idea why this is?
> 
> https://www.ebay.co.uk/itm/PC-Hackintosh-wifi-Card-BCM94352Z-NGFF-WiFi-wlan-Card-867Mbps-Bluetooth-4-0-WiFi/172212358962?hash=item2818a80f32:g:2kEAAOSwQcJfImUy

same card works on t470p (I bought it from Taobao)

**Comment by aptonline** [comment]
Looking at the same card on AliExpress there is reference to the card not working on Lenovo due to the bios whitelist. My understanding is this was only for some earlier Thinkpad models which doesn’t include the T460.

**Comment by NebulaStride-23798** [comment]
> Looking at the same card on AliExpress there is reference to the card not working on Lenovo due to the bios whitelist. My understanding is this was only for some earlier Thinkpad models which doesn’t include the T460.

T460 doesn't have a wireless card whitelist, however now you are able to use intel WiFi pre-installed with your machine by applying [this new driver](https://github.com/OpenIntelWireless/itlwm).

**Comment by aptonline** [comment]
> T460 doesn't have a wireless card whitelist, however now you are able to use intel WiFi pre-installed with your machine by applying [this new driver](https://github.com/OpenIntelWireless/itlwm).

Yeah I saw that... after purchasing a DW1560 the other day.  From what I understand the new driver is very much early in development and the speeds are slow compared so while it’s a great project to keep an eye on I’ll use the one I bought for now 👍.

**Comment by NebulaStride-23798** [comment]
> > T460 doesn't have a wireless card whitelist, however now you are able to use intel WiFi pre-installed with your machine by applying [this new driver](https://github.com/OpenIntelWireless/itlwm).
> 
> Yeah I saw that... after purchasing a DW1560 the other day. From what I understand the new driver is very much early in development and the speeds are slow compared so while it’s a great project to keep an eye on I’ll use the one I bought for now 👍.

In fact, the stable version released yesterday runs well.  Regrading to speed it seems to be acceptable if your WAN connection is less than 100M and not very much concerned about local LAN speed :-)

**Comment by aptonline** [comment]
~~out of interest does the itlwm kext support Bluetooth for handoff and continuity on the T460?~~

Looks like maybe not:  https://github.com/MSzturc/Lenovo-T460-OpenCore/issues/14#issuecomment-679087267

**Comment by aptonline** [comment]
DW1560 installed and working perfectly on my T460.

**Comment by aptonline** [comment]
Spoke too soon, having upload issues: https://github.com/MSzturc/Lenovo-T460-OpenCore/issues/17
