### ISSUE TITLE
Not able to Install Catalina

### ISSUE THREAD

**Issue by MSzturc** [MSzturc/Lenovo-T460-OpenCore#2]
@dunglq2ah

From https://www.insanelymac.com/forum/topic/343588-tool-thinkpad-assistant/?tab=comments#comment-2723665

thanks.  i can question about OC i take EFI of you to install Mac OS but i cant, i get error in pic. Can u see help me?
My laptop T460- 6600- HD520- ALC 293- SSD Intel 256- Broadcom943260cs. I install with clover it OK? BUT OC it stop here.

**Comment by MSzturc** [comment]
To install Catalina you have to add a SMBios that is valid otherwise the installer will quit with this error. Use [GenSMBIOS](https://github.com/corpnewt/GenSMBIOS) for this. I used one for a MacBookPro13,1

**Comment by dunglq2ah** [comment]
thank i will try it. so my laptop T460 - I5 6600  I should BIOS what? and i can get where?
i see smbios for skylake but not for 520.

**Comment by MSzturc** [comment]
Closed - please open an Issue Ticket at GenSMBIOS repository
