### ISSUE TITLE
Build Review

### ISSUE THREAD

**Issue by MSzturc** [MSzturc/Lenovo-T460-OpenCore#4]
@tylernguyen
I would like to know if there are any enhancements you would do on my T460 build. Technically it's working stable for over 2 months on daily use. I want to know if you see unnecessary acpi patches or kext i could cleanup

**Comment by tylernguyen** [comment]
@MSzturc Of course, please give me some time to review the repo.

**Comment by tylernguyen** [comment]
@MSzturc I don't have first hand experience with your machine nor a T460 to test your repo with. However, I can say the following after a while reviewing your repo:
* I do not think `EFICheckDisabler` is needed. I have never experienced a check post Sierra/ High Sierra. You should remove this kext until you get an EFI check.
* `config.plist` doesn't seem to be setup for FileVault. I recommend you to use FileVault for better security, especially for a hackintosh.
* You have `RTCMemoryFixup` installed but no boot-args injected?

But overall, the build looks good! `config.plist` and EFI folders are both very clean. I do have some questions for your SSDT setup though:
* I found the way you organize your patches very interesting, are there any tangible benefits to this setup other than a cleaner patch level structure?

**Comment by MSzturc** [comment]
Thx for the input! Removed EFICheckDisabler and put FileVault on my Todo List. RTCMemoryFixup works fine without excludes for me. Can you describe bugs that occur when excludes are missing?

**Comment by tylernguyen** [comment]
@MSzturc 

I'm under the impression that RTCMemoryFixup is only used to exclude some CMOS ranges. It does nothing by default.

See https://github.com/acidanthera/bugtracker/issues/788#issuecomment-604608329
